//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.08 at 02:44:38 PM SGT 
//


package com.onsemi.cdars.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="emailB4Day" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="userPKIDList" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemType",
    "emailB4Day",
    "userPKIDList"
})
@XmlRootElement(name = "InsertExpiryNotice")
public class InsertExpiryNotice {

    protected String itemType;
    protected int emailB4Day;
    protected String userPKIDList;

    /**
     * Gets the value of the itemType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * Sets the value of the itemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemType(String value) {
        this.itemType = value;
    }

    /**
     * Gets the value of the emailB4Day property.
     * 
     */
    public int getEmailB4Day() {
        return emailB4Day;
    }

    /**
     * Sets the value of the emailB4Day property.
     * 
     */
    public void setEmailB4Day(int value) {
        this.emailB4Day = value;
    }

    /**
     * Gets the value of the userPKIDList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserPKIDList() {
        return userPKIDList;
    }

    /**
     * Sets the value of the userPKIDList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserPKIDList(String value) {
        this.userPKIDList = value;
    }

}
