//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.23 at 02:38:22 PM SGT 
//


package com.onsemi.cdars.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.onsemi.cdars.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.onsemi.cdars.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteSite }
     * 
     */
    public DeleteSite createDeleteSite() {
        return new DeleteSite();
    }

    /**
     * Create an instance of {@link UpdateSite }
     * 
     */
    public UpdateSite createUpdateSite() {
        return new UpdateSite();
    }

    /**
     * Create an instance of {@link UpdateCDARSStatus }
     * 
     */
    public UpdateCDARSStatus createUpdateCDARSStatus() {
        return new UpdateCDARSStatus();
    }

    /**
     * Create an instance of {@link UpdateScore }
     * 
     */
    public UpdateScore createUpdateScore() {
        return new UpdateScore();
    }

    /**
     * Create an instance of {@link DeleteExpiryNotice }
     * 
     */
    public DeleteExpiryNotice createDeleteExpiryNotice() {
        return new DeleteExpiryNotice();
    }

    /**
     * Create an instance of {@link GetItemByPKID }
     * 
     */
    public GetItemByPKID createGetItemByPKID() {
        return new GetItemByPKID();
    }

    /**
     * Create an instance of {@link UpdateScoreNDetailsResponse }
     * 
     */
    public UpdateScoreNDetailsResponse createUpdateScoreNDetailsResponse() {
        return new UpdateScoreNDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateUserPasswordResponse }
     * 
     */
    public UpdateUserPasswordResponse createUpdateUserPasswordResponse() {
        return new UpdateUserPasswordResponse();
    }

    /**
     * Create an instance of {@link InsertScoreResponse }
     * 
     */
    public InsertScoreResponse createInsertScoreResponse() {
        return new InsertScoreResponse();
    }

    /**
     * Create an instance of {@link GetEffortNBenefitByParamResponse }
     * 
     */
    public GetEffortNBenefitByParamResponse createGetEffortNBenefitByParamResponse() {
        return new GetEffortNBenefitByParamResponse();
    }

    /**
     * Create an instance of {@link GetEffortNBenefitByParam }
     * 
     */
    public GetEffortNBenefitByParam createGetEffortNBenefitByParam() {
        return new GetEffortNBenefitByParam();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link GetSitesByParam }
     * 
     */
    public GetSitesByParam createGetSitesByParam() {
        return new GetSitesByParam();
    }

    /**
     * Create an instance of {@link InsertScoreNDetailsResponse }
     * 
     */
    public InsertScoreNDetailsResponse createInsertScoreNDetailsResponse() {
        return new InsertScoreNDetailsResponse();
    }

    /**
     * Create an instance of {@link InsertTransaction }
     * 
     */
    public InsertTransaction createInsertTransaction() {
        return new InsertTransaction();
    }

    /**
     * Create an instance of {@link UpdateScoreResponse }
     * 
     */
    public UpdateScoreResponse createUpdateScoreResponse() {
        return new UpdateScoreResponse();
    }

    /**
     * Create an instance of {@link UpdateSiteResponse }
     * 
     */
    public UpdateSiteResponse createUpdateSiteResponse() {
        return new UpdateSiteResponse();
    }

    /**
     * Create an instance of {@link InsertUserResponse }
     * 
     */
    public InsertUserResponse createInsertUserResponse() {
        return new InsertUserResponse();
    }

    /**
     * Create an instance of {@link UpdateSites }
     * 
     */
    public UpdateSites createUpdateSites() {
        return new UpdateSites();
    }

    /**
     * Create an instance of {@link DeleteScoreDetail }
     * 
     */
    public DeleteScoreDetail createDeleteScoreDetail() {
        return new DeleteScoreDetail();
    }

    /**
     * Create an instance of {@link InsertSitesResponse }
     * 
     */
    public InsertSitesResponse createInsertSitesResponse() {
        return new InsertSitesResponse();
    }

    /**
     * Create an instance of {@link DeleteRackResponse }
     * 
     */
    public DeleteRackResponse createDeleteRackResponse() {
        return new DeleteRackResponse();
    }

    /**
     * Create an instance of {@link InsertScoreDetailsResponse }
     * 
     */
    public InsertScoreDetailsResponse createInsertScoreDetailsResponse() {
        return new InsertScoreDetailsResponse();
    }

    /**
     * Create an instance of {@link GetActivityLogByParam }
     * 
     */
    public GetActivityLogByParam createGetActivityLogByParam() {
        return new GetActivityLogByParam();
    }

    /**
     * Create an instance of {@link GetItemTypeAllResponse }
     * 
     */
    public GetItemTypeAllResponse createGetItemTypeAllResponse() {
        return new GetItemTypeAllResponse();
    }

    /**
     * Create an instance of {@link InsertExpiryNoticeData }
     * 
     */
    public InsertExpiryNoticeData createInsertExpiryNoticeData() {
        return new InsertExpiryNoticeData();
    }

    /**
     * Create an instance of {@link UpdateItemResponse }
     * 
     */
    public UpdateItemResponse createUpdateItemResponse() {
        return new UpdateItemResponse();
    }

    /**
     * Create an instance of {@link InsertScoresResponse }
     * 
     */
    public InsertScoresResponse createInsertScoresResponse() {
        return new InsertScoresResponse();
    }

    /**
     * Create an instance of {@link UpdateScoreDetailsResponse }
     * 
     */
    public UpdateScoreDetailsResponse createUpdateScoreDetailsResponse() {
        return new UpdateScoreDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteItem }
     * 
     */
    public DeleteItem createDeleteItem() {
        return new DeleteItem();
    }

    /**
     * Create an instance of {@link InsertScoreDetailResponse }
     * 
     */
    public InsertScoreDetailResponse createInsertScoreDetailResponse() {
        return new InsertScoreDetailResponse();
    }

    /**
     * Create an instance of {@link DeleteScoreDetailsResponse }
     * 
     */
    public DeleteScoreDetailsResponse createDeleteScoreDetailsResponse() {
        return new DeleteScoreDetailsResponse();
    }

    /**
     * Create an instance of {@link DisposeItemResponse }
     * 
     */
    public DisposeItemResponse createDisposeItemResponse() {
        return new DisposeItemResponse();
    }

    /**
     * Create an instance of {@link DeleteUser }
     * 
     */
    public DeleteUser createDeleteUser() {
        return new DeleteUser();
    }

    /**
     * Create an instance of {@link GetUserByUserID }
     * 
     */
    public GetUserByUserID createGetUserByUserID() {
        return new GetUserByUserID();
    }

    /**
     * Create an instance of {@link InsertSiteResponse }
     * 
     */
    public InsertSiteResponse createInsertSiteResponse() {
        return new InsertSiteResponse();
    }

    /**
     * Create an instance of {@link UpdateSystemSettings }
     * 
     */
    public UpdateSystemSettings createUpdateSystemSettings() {
        return new UpdateSystemSettings();
    }

    /**
     * Create an instance of {@link GetScoreNDetailsAll }
     * 
     */
    public GetScoreNDetailsAll createGetScoreNDetailsAll() {
        return new GetScoreNDetailsAll();
    }

    /**
     * Create an instance of {@link DeleteExpiryNoticeResponse }
     * 
     */
    public DeleteExpiryNoticeResponse createDeleteExpiryNoticeResponse() {
        return new DeleteExpiryNoticeResponse();
    }

    /**
     * Create an instance of {@link UpdateItemStatusResponse }
     * 
     */
    public UpdateItemStatusResponse createUpdateItemStatusResponse() {
        return new UpdateItemStatusResponse();
    }

    /**
     * Create an instance of {@link GetExpiryNoticeByParam }
     * 
     */
    public GetExpiryNoticeByParam createGetExpiryNoticeByParam() {
        return new GetExpiryNoticeByParam();
    }

    /**
     * Create an instance of {@link InsertExpiryNoticeResponse }
     * 
     */
    public InsertExpiryNoticeResponse createInsertExpiryNoticeResponse() {
        return new InsertExpiryNoticeResponse();
    }

    /**
     * Create an instance of {@link DeleteScoreNDetails }
     * 
     */
    public DeleteScoreNDetails createDeleteScoreNDetails() {
        return new DeleteScoreNDetails();
    }

    /**
     * Create an instance of {@link GetScoresAllResponse }
     * 
     */
    public GetScoresAllResponse createGetScoresAllResponse() {
        return new GetScoresAllResponse();
    }

    /**
     * Create an instance of {@link GetSitesByParamResponse }
     * 
     */
    public GetSitesByParamResponse createGetSitesByParamResponse() {
        return new GetSitesByParamResponse();
    }

    /**
     * Create an instance of {@link GetScoresAll }
     * 
     */
    public GetScoresAll createGetScoresAll() {
        return new GetScoresAll();
    }

    /**
     * Create an instance of {@link DeleteScoreDetails }
     * 
     */
    public DeleteScoreDetails createDeleteScoreDetails() {
        return new DeleteScoreDetails();
    }

    /**
     * Create an instance of {@link UpdateExpiryNoticeResponse }
     * 
     */
    public UpdateExpiryNoticeResponse createUpdateExpiryNoticeResponse() {
        return new UpdateExpiryNoticeResponse();
    }

    /**
     * Create an instance of {@link GetSitesAllResponse }
     * 
     */
    public GetSitesAllResponse createGetSitesAllResponse() {
        return new GetSitesAllResponse();
    }

    /**
     * Create an instance of {@link DeleteScores }
     * 
     */
    public DeleteScores createDeleteScores() {
        return new DeleteScores();
    }

    /**
     * Create an instance of {@link InsertItemResponse }
     * 
     */
    public InsertItemResponse createInsertItemResponse() {
        return new InsertItemResponse();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link UpdateItem }
     * 
     */
    public UpdateItem createUpdateItem() {
        return new UpdateItem();
    }

    /**
     * Create an instance of {@link InsertScoreDetails }
     * 
     */
    public InsertScoreDetails createInsertScoreDetails() {
        return new InsertScoreDetails();
    }

    /**
     * Create an instance of {@link GetTransactionByParamResponse }
     * 
     */
    public GetTransactionByParamResponse createGetTransactionByParamResponse() {
        return new GetTransactionByParamResponse();
    }

    /**
     * Create an instance of {@link GetItemByParamResponse }
     * 
     */
    public GetItemByParamResponse createGetItemByParamResponse() {
        return new GetItemByParamResponse();
    }

    /**
     * Create an instance of {@link DeleteScore }
     * 
     */
    public DeleteScore createDeleteScore() {
        return new DeleteScore();
    }

    /**
     * Create an instance of {@link GetScoreDetailsByParam }
     * 
     */
    public GetScoreDetailsByParam createGetScoreDetailsByParam() {
        return new GetScoreDetailsByParam();
    }

    /**
     * Create an instance of {@link DeleteScoreDetailResponse }
     * 
     */
    public DeleteScoreDetailResponse createDeleteScoreDetailResponse() {
        return new DeleteScoreDetailResponse();
    }

    /**
     * Create an instance of {@link GetItemByParam }
     * 
     */
    public GetItemByParam createGetItemByParam() {
        return new GetItemByParam();
    }

    /**
     * Create an instance of {@link InsertSites }
     * 
     */
    public InsertSites createInsertSites() {
        return new InsertSites();
    }

    /**
     * Create an instance of {@link GetUserByUserIDResponse }
     * 
     */
    public GetUserByUserIDResponse createGetUserByUserIDResponse() {
        return new GetUserByUserIDResponse();
    }

    /**
     * Create an instance of {@link DeleteSiteResponse }
     * 
     */
    public DeleteSiteResponse createDeleteSiteResponse() {
        return new DeleteSiteResponse();
    }

    /**
     * Create an instance of {@link UpdateSystemSettingResponse }
     * 
     */
    public UpdateSystemSettingResponse createUpdateSystemSettingResponse() {
        return new UpdateSystemSettingResponse();
    }

    /**
     * Create an instance of {@link InsertScoreNDetails }
     * 
     */
    public InsertScoreNDetails createInsertScoreNDetails() {
        return new InsertScoreNDetails();
    }

    /**
     * Create an instance of {@link InsertExpiryNoticeDataResponse }
     * 
     */
    public InsertExpiryNoticeDataResponse createInsertExpiryNoticeDataResponse() {
        return new InsertExpiryNoticeDataResponse();
    }

    /**
     * Create an instance of {@link InsertSite }
     * 
     */
    public InsertSite createInsertSite() {
        return new InsertSite();
    }

    /**
     * Create an instance of {@link InsertSystemSetting }
     * 
     */
    public InsertSystemSetting createInsertSystemSetting() {
        return new InsertSystemSetting();
    }

    /**
     * Create an instance of {@link DeleteScoreNDetailsResponse }
     * 
     */
    public DeleteScoreNDetailsResponse createDeleteScoreNDetailsResponse() {
        return new DeleteScoreNDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateUserPassword }
     * 
     */
    public UpdateUserPassword createUpdateUserPassword() {
        return new UpdateUserPassword();
    }

    /**
     * Create an instance of {@link InsertRack }
     * 
     */
    public InsertRack createInsertRack() {
        return new InsertRack();
    }

    /**
     * Create an instance of {@link UpdateAllowedSitePKIDListByNameResponse }
     * 
     */
    public UpdateAllowedSitePKIDListByNameResponse createUpdateAllowedSitePKIDListByNameResponse() {
        return new UpdateAllowedSitePKIDListByNameResponse();
    }

    /**
     * Create an instance of {@link UpdateItemStatus }
     * 
     */
    public UpdateItemStatus createUpdateItemStatus() {
        return new UpdateItemStatus();
    }

    /**
     * Create an instance of {@link GetTransactionByPKID }
     * 
     */
    public GetTransactionByPKID createGetTransactionByPKID() {
        return new GetTransactionByPKID();
    }

    /**
     * Create an instance of {@link InsertActivityLogResponse }
     * 
     */
    public InsertActivityLogResponse createInsertActivityLogResponse() {
        return new InsertActivityLogResponse();
    }

    /**
     * Create an instance of {@link DeleteScoresResponse }
     * 
     */
    public DeleteScoresResponse createDeleteScoresResponse() {
        return new DeleteScoresResponse();
    }

    /**
     * Create an instance of {@link UpdateUser }
     * 
     */
    public UpdateUser createUpdateUser() {
        return new UpdateUser();
    }

    /**
     * Create an instance of {@link GetTransactionByPKIDResponse }
     * 
     */
    public GetTransactionByPKIDResponse createGetTransactionByPKIDResponse() {
        return new GetTransactionByPKIDResponse();
    }

    /**
     * Create an instance of {@link UpdateSitesResponse }
     * 
     */
    public UpdateSitesResponse createUpdateSitesResponse() {
        return new UpdateSitesResponse();
    }

    /**
     * Create an instance of {@link InsertScoreDetail }
     * 
     */
    public InsertScoreDetail createInsertScoreDetail() {
        return new InsertScoreDetail();
    }

    /**
     * Create an instance of {@link InsertExpiryNotice }
     * 
     */
    public InsertExpiryNotice createInsertExpiryNotice() {
        return new InsertExpiryNotice();
    }

    /**
     * Create an instance of {@link GetScoreDetailsAll }
     * 
     */
    public GetScoreDetailsAll createGetScoreDetailsAll() {
        return new GetScoreDetailsAll();
    }

    /**
     * Create an instance of {@link DeleteTransaction }
     * 
     */
    public DeleteTransaction createDeleteTransaction() {
        return new DeleteTransaction();
    }

    /**
     * Create an instance of {@link UpdateScoreNDetails }
     * 
     */
    public UpdateScoreNDetails createUpdateScoreNDetails() {
        return new UpdateScoreNDetails();
    }

    /**
     * Create an instance of {@link GetItemAll }
     * 
     */
    public GetItemAll createGetItemAll() {
        return new GetItemAll();
    }

    /**
     * Create an instance of {@link GetExpiryNoticeAllResponse }
     * 
     */
    public GetExpiryNoticeAllResponse createGetExpiryNoticeAllResponse() {
        return new GetExpiryNoticeAllResponse();
    }

    /**
     * Create an instance of {@link GetItemTransactionByParam }
     * 
     */
    public GetItemTransactionByParam createGetItemTransactionByParam() {
        return new GetItemTransactionByParam();
    }

    /**
     * Create an instance of {@link DeleteScoreResponse }
     * 
     */
    public DeleteScoreResponse createDeleteScoreResponse() {
        return new DeleteScoreResponse();
    }

    /**
     * Create an instance of {@link UpdateScoreDetails }
     * 
     */
    public UpdateScoreDetails createUpdateScoreDetails() {
        return new UpdateScoreDetails();
    }

    /**
     * Create an instance of {@link DeleteTransactionResponse }
     * 
     */
    public DeleteTransactionResponse createDeleteTransactionResponse() {
        return new DeleteTransactionResponse();
    }

    /**
     * Create an instance of {@link GetSitesAll }
     * 
     */
    public GetSitesAll createGetSitesAll() {
        return new GetSitesAll();
    }

    /**
     * Create an instance of {@link UpdateTransaction }
     * 
     */
    public UpdateTransaction createUpdateTransaction() {
        return new UpdateTransaction();
    }

    /**
     * Create an instance of {@link GetItemTransactionByParamResponse }
     * 
     */
    public GetItemTransactionByParamResponse createGetItemTransactionByParamResponse() {
        return new GetItemTransactionByParamResponse();
    }

    /**
     * Create an instance of {@link GetScoreDetailsAllResponse }
     * 
     */
    public GetScoreDetailsAllResponse createGetScoreDetailsAllResponse() {
        return new GetScoreDetailsAllResponse();
    }

    /**
     * Create an instance of {@link GetUserAllResponse }
     * 
     */
    public GetUserAllResponse createGetUserAllResponse() {
        return new GetUserAllResponse();
    }

    /**
     * Create an instance of {@link GetScoreNDetailsByParam }
     * 
     */
    public GetScoreNDetailsByParam createGetScoreNDetailsByParam() {
        return new GetScoreNDetailsByParam();
    }

    /**
     * Create an instance of {@link GetExpiryNoticeAll }
     * 
     */
    public GetExpiryNoticeAll createGetExpiryNoticeAll() {
        return new GetExpiryNoticeAll();
    }

    /**
     * Create an instance of {@link InsertSystemSettingResponse }
     * 
     */
    public InsertSystemSettingResponse createInsertSystemSettingResponse() {
        return new InsertSystemSettingResponse();
    }

    /**
     * Create an instance of {@link GetScoreNDetailsAllResponse }
     * 
     */
    public GetScoreNDetailsAllResponse createGetScoreNDetailsAllResponse() {
        return new GetScoreNDetailsAllResponse();
    }

    /**
     * Create an instance of {@link UpdateScoreDetailResponse }
     * 
     */
    public UpdateScoreDetailResponse createUpdateScoreDetailResponse() {
        return new UpdateScoreDetailResponse();
    }

    /**
     * Create an instance of {@link SynchronizeSitesNSiteAllowedResponse }
     * 
     */
    public SynchronizeSitesNSiteAllowedResponse createSynchronizeSitesNSiteAllowedResponse() {
        return new SynchronizeSitesNSiteAllowedResponse();
    }

    /**
     * Create an instance of {@link GetCardTypeAllResponse }
     * 
     */
    public GetCardTypeAllResponse createGetCardTypeAllResponse() {
        return new GetCardTypeAllResponse();
    }

    /**
     * Create an instance of {@link GetItemAllResponse }
     * 
     */
    public GetItemAllResponse createGetItemAllResponse() {
        return new GetItemAllResponse();
    }

    /**
     * Create an instance of {@link GetActivityLogByParamResponse }
     * 
     */
    public GetActivityLogByParamResponse createGetActivityLogByParamResponse() {
        return new GetActivityLogByParamResponse();
    }

    /**
     * Create an instance of {@link GetTransactionAll }
     * 
     */
    public GetTransactionAll createGetTransactionAll() {
        return new GetTransactionAll();
    }

    /**
     * Create an instance of {@link GetTransactionByParam }
     * 
     */
    public GetTransactionByParam createGetTransactionByParam() {
        return new GetTransactionByParam();
    }

    /**
     * Create an instance of {@link DisposeItem }
     * 
     */
    public DisposeItem createDisposeItem() {
        return new DisposeItem();
    }

    /**
     * Create an instance of {@link GetItemTypeAll }
     * 
     */
    public GetItemTypeAll createGetItemTypeAll() {
        return new GetItemTypeAll();
    }

    /**
     * Create an instance of {@link GetExpiryNoticeByParamResponse }
     * 
     */
    public GetExpiryNoticeByParamResponse createGetExpiryNoticeByParamResponse() {
        return new GetExpiryNoticeByParamResponse();
    }

    /**
     * Create an instance of {@link GetScoresByParamResponse }
     * 
     */
    public GetScoresByParamResponse createGetScoresByParamResponse() {
        return new GetScoresByParamResponse();
    }

    /**
     * Create an instance of {@link UpdateSystemSettingsResponse }
     * 
     */
    public UpdateSystemSettingsResponse createUpdateSystemSettingsResponse() {
        return new UpdateSystemSettingsResponse();
    }

    /**
     * Create an instance of {@link UpdateScores }
     * 
     */
    public UpdateScores createUpdateScores() {
        return new UpdateScores();
    }

    /**
     * Create an instance of {@link GetTransactionAllResponse }
     * 
     */
    public GetTransactionAllResponse createGetTransactionAllResponse() {
        return new GetTransactionAllResponse();
    }

    /**
     * Create an instance of {@link InsertItem }
     * 
     */
    public InsertItem createInsertItem() {
        return new InsertItem();
    }

    /**
     * Create an instance of {@link InsertScores }
     * 
     */
    public InsertScores createInsertScores() {
        return new InsertScores();
    }

    /**
     * Create an instance of {@link InsertUser }
     * 
     */
    public InsertUser createInsertUser() {
        return new InsertUser();
    }

    /**
     * Create an instance of {@link UpdateExpiryNotice }
     * 
     */
    public UpdateExpiryNotice createUpdateExpiryNotice() {
        return new UpdateExpiryNotice();
    }

    /**
     * Create an instance of {@link UpdateTransactionResponse }
     * 
     */
    public UpdateTransactionResponse createUpdateTransactionResponse() {
        return new UpdateTransactionResponse();
    }

    /**
     * Create an instance of {@link InsertScore }
     * 
     */
    public InsertScore createInsertScore() {
        return new InsertScore();
    }

    /**
     * Create an instance of {@link DeleteRack }
     * 
     */
    public DeleteRack createDeleteRack() {
        return new DeleteRack();
    }

    /**
     * Create an instance of {@link GetSystemSettingAll }
     * 
     */
    public GetSystemSettingAll createGetSystemSettingAll() {
        return new GetSystemSettingAll();
    }

    /**
     * Create an instance of {@link GetRackAll }
     * 
     */
    public GetRackAll createGetRackAll() {
        return new GetRackAll();
    }

    /**
     * Create an instance of {@link GetUserAll }
     * 
     */
    public GetUserAll createGetUserAll() {
        return new GetUserAll();
    }

    /**
     * Create an instance of {@link InsertRackResponse }
     * 
     */
    public InsertRackResponse createInsertRackResponse() {
        return new InsertRackResponse();
    }

    /**
     * Create an instance of {@link GetScoreDetailsByParamResponse }
     * 
     */
    public GetScoreDetailsByParamResponse createGetScoreDetailsByParamResponse() {
        return new GetScoreDetailsByParamResponse();
    }

    /**
     * Create an instance of {@link SynchronizeSitesNSiteAllowed }
     * 
     */
    public SynchronizeSitesNSiteAllowed createSynchronizeSitesNSiteAllowed() {
        return new SynchronizeSitesNSiteAllowed();
    }

    /**
     * Create an instance of {@link InsertActivityLog }
     * 
     */
    public InsertActivityLog createInsertActivityLog() {
        return new InsertActivityLog();
    }

    /**
     * Create an instance of {@link GetUserByParamResponse }
     * 
     */
    public GetUserByParamResponse createGetUserByParamResponse() {
        return new GetUserByParamResponse();
    }

    /**
     * Create an instance of {@link UpdateScoresResponse }
     * 
     */
    public UpdateScoresResponse createUpdateScoresResponse() {
        return new UpdateScoresResponse();
    }

    /**
     * Create an instance of {@link UpdateCDARSStatusResponse }
     * 
     */
    public UpdateCDARSStatusResponse createUpdateCDARSStatusResponse() {
        return new UpdateCDARSStatusResponse();
    }

    /**
     * Create an instance of {@link GetCardTypeAll }
     * 
     */
    public GetCardTypeAll createGetCardTypeAll() {
        return new GetCardTypeAll();
    }

    /**
     * Create an instance of {@link DeleteItemResponse }
     * 
     */
    public DeleteItemResponse createDeleteItemResponse() {
        return new DeleteItemResponse();
    }

    /**
     * Create an instance of {@link GetScoreNDetailsByParamResponse }
     * 
     */
    public GetScoreNDetailsByParamResponse createGetScoreNDetailsByParamResponse() {
        return new GetScoreNDetailsByParamResponse();
    }

    /**
     * Create an instance of {@link GetScoresByParam }
     * 
     */
    public GetScoresByParam createGetScoresByParam() {
        return new GetScoresByParam();
    }

    /**
     * Create an instance of {@link GetRackAllResponse }
     * 
     */
    public GetRackAllResponse createGetRackAllResponse() {
        return new GetRackAllResponse();
    }

    /**
     * Create an instance of {@link UpdateSystemSetting }
     * 
     */
    public UpdateSystemSetting createUpdateSystemSetting() {
        return new UpdateSystemSetting();
    }

    /**
     * Create an instance of {@link GetSystemSettingAllResponse }
     * 
     */
    public GetSystemSettingAllResponse createGetSystemSettingAllResponse() {
        return new GetSystemSettingAllResponse();
    }

    /**
     * Create an instance of {@link InsertTransactionResponse }
     * 
     */
    public InsertTransactionResponse createInsertTransactionResponse() {
        return new InsertTransactionResponse();
    }

    /**
     * Create an instance of {@link GetItemByPKIDResponse }
     * 
     */
    public GetItemByPKIDResponse createGetItemByPKIDResponse() {
        return new GetItemByPKIDResponse();
    }

    /**
     * Create an instance of {@link UpdateAllowedSitePKIDListByName }
     * 
     */
    public UpdateAllowedSitePKIDListByName createUpdateAllowedSitePKIDListByName() {
        return new UpdateAllowedSitePKIDListByName();
    }

    /**
     * Create an instance of {@link GetUserByParam }
     * 
     */
    public GetUserByParam createGetUserByParam() {
        return new GetUserByParam();
    }

    /**
     * Create an instance of {@link UpdateScoreDetail }
     * 
     */
    public UpdateScoreDetail createUpdateScoreDetail() {
        return new UpdateScoreDetail();
    }

}
